trigger:
- none

pr:
- none

variables:
  variables:
  location: "eastus"
  solutionName: "ITMSDevBox"
  devBoxResourceGroupName: "IT-MSDevBox-POC"
  bicepArtifactsPath: '$(Build.SourcesDirectory)/bicepArtifacts'
  connectivityResourceGroupName: "ITMSDevBox-DevExp-Connectivity-RG"

jobs:

- job: Deploy
  displayName: 'Deploy Microsoft DevBox Resources to Azure'
  dependsOn: Build
  pool:
    name: Linux
  steps:
  - checkout: self
    displayName: 'Checkout Source Code'

  # Grant execute permissions to the deployment script
  - task: Bash@3
    displayName: 'Grant permissions to the Script'
    inputs:
      targetType: 'inline'
      script: |
        chmod +x ./src/deploy/bicep/bash/deployResourcesOrganization.sh

  # Deploy the Landing Zone Resources using the deployment script
  - task: AzureCLI@2
    displayName: 'Deploy Landing Zone Resources'
    inputs:
      azureSubscription: devOps
      scriptType: 'bash'
      scriptLocation: 'inlineScript'
      inlineScript: |
        ./src/deploy/bicep/bash/deployResourcesOrganization.sh $(devBoxResourceGroupName) $(location)

  # Deploy the Dev Box Management Resources to Azure
  - task: AzureCLI@2
    displayName: 'Deploy Dev Box Resources to Azure'
    inputs:
      azureSubscription: devOps
      scriptType: 'bash'
      scriptLocation: 'inlineScript'
      inlineScript: |
        az deployment group create \
          --name 'Deploy-DevBox-Resources' \
          --resource-group $(devBoxResourceGroupName) \
          --template-file ./src/deploy/bicep/deploy.bicep \
          --parameters solutionName=$(solutionName) \
          --mode Incremental 

        az deployment group create  \
            --name 'Deploy-DevBox-Resources'
            --resource-group $(devBoxResourceGroupName) \
            --template-file ./deploy/deploy.bicep \
            --parameters ./deploy/params.bicepparam \
            --parameters workloadName=$(solutionName) \
                rgConnectivityName=$(connectivityResourceGroupName) \
            --mode Incremental