trigger:
- none

pr:
- none

variables:
  variables:
  location: "eastus2"
  solutionName: "ITMSDevBox"
  devBoxResourceGroupName: "IT-MSDevBox-POC"
  bicepArtifactsPath: '$(Build.SourcesDirectory)/bicepArtifacts'
  connectivityResourceGroupName: "IT-MSDevBox-POC"

jobs:

- job: Deploy
  displayName: 'Deploy Microsoft DevBox Resources to Azure'
  pool:
    name: Linux
  steps:
  - checkout: self
    displayName: 'Checkout Source Code'

  # Deploy the Dev Box Management Resources to Azure
  - task: AzureCLI@2
    displayName: 'Deploy Dev Box Resources to Azure'
    inputs:
      azureSubscription: devOps
      scriptType: 'bash'
      scriptLocation: 'inlineScript'
      inlineScript: |
        az deployment group create  \
            --name 'Deploy-DevBox-Resources'
            --resource-group $(devBoxResourceGroupName) \
            --template-file ./deploy/deploy.bicep \
            --parameters ./deploy/params.bicepparam \
            --parameters workloadName=$(solutionName) \
                rgConnectivityName=$(connectivityResourceGroupName) \
            --mode Incremental